# Generated by Django 5.0.6 on 2025-06-18 18:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSHomeSec1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='page_name')),
                ('page_slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='page_slug')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('button_text_1', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url_1', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('button_text_2', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url_2', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('image', models.FileField(blank=True, upload_to='page', verbose_name='media')),
                ('card_1_title', models.CharField(blank=True, max_length=100, verbose_name='card_1_title')),
                ('card_1_description', models.TextField(blank=True, max_length=300, verbose_name='card_1_description')),
                ('card_1_icon', models.CharField(blank=True, max_length=100, verbose_name='card_1_icon (FontAwesome class)')),
                ('card_2_title', models.CharField(blank=True, max_length=100, verbose_name='card_2_title')),
                ('card_2_description', models.TextField(blank=True, max_length=300, verbose_name='card_2_description')),
                ('card_2_icon', models.CharField(blank=True, max_length=100, verbose_name='card_2_icon (FontAwesome class)')),
            ],
        ),
        migrations.CreateModel(
            name='CMSHomeSec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('button_text_1', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url_1', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('button_text_2', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url_2', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('image', models.FileField(blank=True, upload_to='page', verbose_name='media')),
                ('card_1_title', models.CharField(blank=True, max_length=100, verbose_name='card_1_title')),
                ('card_1_description', models.TextField(blank=True, max_length=300, verbose_name='card_1_description')),
                ('card_1_icon', models.CharField(blank=True, max_length=100, verbose_name='card_1_icon (FontAwesome class)')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('num_title', models.CharField(blank=True, max_length=100, verbose_name='card_2_num_title')),
                ('card_2_description', models.TextField(blank=True, max_length=300, verbose_name='card_2_description')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='logo')),
            ],
        ),
    ]
