# Generated by Django 5.0.6 on 2025-06-18 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='page_name')),
                ('page_slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='page_slug')),
                ('section_name', models.CharField(max_length=50, verbose_name='section_name')),
                ('section_slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='section_slug')),
                ('header_title', models.CharField(max_length=100, verbose_name='Header Title')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Sub Title')),
                ('short_description', models.TextField(max_length=200, verbose_name='Short Description')),
                ('short_description_2', models.TextField(blank=True, max_length=200, null=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('content_block_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Primary Content Block')),
                ('content_block_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Secondary Content Block')),
                ('content_block_3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tertiary Content Block')),
                ('button_text_1', models.CharField(blank=True, max_length=50, verbose_name='Primary Button Text')),
                ('button_url_1', models.URLField(blank=True, verbose_name='Primary Button URL')),
                ('button_text_2', models.CharField(blank=True, max_length=50, verbose_name='Secondary Button Text')),
                ('button_url_2', models.URLField(blank=True, verbose_name='Secondary Button URL')),
                ('button_text_3', models.CharField(blank=True, max_length=50, verbose_name='Tertiary Button Text')),
                ('button_url_3', models.URLField(blank=True, verbose_name='Tertiary Button URL')),
                ('media_1', models.FileField(blank=True, upload_to='page/media/', verbose_name='media_1')),
                ('media_2', models.FileField(blank=True, upload_to='page/media/', verbose_name='media_2')),
                ('media_3', models.FileField(blank=True, upload_to='page/media/', verbose_name='media_3')),
                ('icon_1', models.CharField(blank=True, max_length=100, verbose_name='icon_1 (FontAwesome class)')),
                ('icon_2', models.CharField(blank=True, max_length=100, verbose_name='icon_2 (FontAwesome class)')),
                ('icon_3', models.CharField(blank=True, max_length=100, verbose_name='icon_3 (FontAwesome class)')),
                ('card_1_title', models.CharField(blank=True, max_length=100, verbose_name='card_1_title')),
                ('card_1_description', models.TextField(blank=True, max_length=300, verbose_name='card_1_description')),
                ('card_1_icon', models.CharField(blank=True, max_length=100, verbose_name='card_1_icon (FontAwesome class)')),
                ('card_2_title', models.CharField(blank=True, max_length=100, verbose_name='card_2_title')),
                ('card_2_description', models.TextField(blank=True, max_length=300, verbose_name='card_2_description')),
                ('card_2_icon', models.CharField(blank=True, max_length=100, verbose_name='card_2_icon (FontAwesome class)')),
                ('card_3_title', models.CharField(blank=True, max_length=100, verbose_name='card_3_title')),
                ('card_3_description', models.TextField(blank=True, max_length=300, verbose_name='card_3_description')),
                ('card_3_icon', models.CharField(blank=True, max_length=100, verbose_name='card_3_icon (FontAwesome class)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'ordering': ['order', 'page_name'],
            },
        ),
        migrations.DeleteModel(
            name='CMSHomeSec1',
        ),
        migrations.DeleteModel(
            name='CMSHomeSec2',
        ),
        migrations.DeleteModel(
            name='PartnerLogo',
        ),
    ]
